const responseCodeConstant = {
	"SUCCESS": 200,
	"INTERNAL_SERVER_ERROR": 500,
	"MISSING_HEADERS": 100,
	"INVALID_DEVICE_TYPE": 101,
	"INVALID EMAIL OR PASSWORD":106,
	"INVALID_LOGIN_CREDENTIALS": 111,
	"INVALID_API_KEY": 102,
	"ACCESS_TOKEN_REQUIRED": 103,
	"INVALID_TOKEN": 104,
	"VALIDATION_ERROR": 105,
	"USER_NOT_FOUND": 107,
	"USER_ACCOUNT_BLOCKED": 108,
	"SOCIAL_USER_NOT_FOUND": 109,
	"ACCESS_DENIED_FOR_THIS_USER": 110,
	"LOGOUT_SUCCESS": 200,
	"EMAIL_ALREADY_EXIST": 112,
	"INACTIVE_USER": 113,
	"ONLY_ADMIN_ALLOWED": 114,
	"INVALID_USER_ID": 127,
	"INVALID_ATTENDANCE_ID": 128,
	"ALREADY_PUNCHED_IN_TODAY": 115,
	"PUNCH_IN_REQUIRED": 116,
	"ALREADY_PUNCHED_OUT": 117,
	"ONLY_ADMIN_AND_HR_ALLOWED": 118,
	"EMP_CODE_ALREADY_EXIST": 119
}

export default responseCodeConstant;